// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhqssmdtcepjjovkryue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhocXNzbWR0Y2VwampvdmtyeXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTU5NzYsImV4cCI6MjA2MDg5MTk3Nn0.hIqwm9VPksnXHYfLuAX9w909bTPm1CucNiyUKsTt84k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);